USE PROBLEMS;
-- What is the total amount each customer spent at the restaurant?
SELECT * FROM SALES;
SELECT * FROM MEMBERS;
SELECT * FROM MENU;

SELECT S.CUSTOMER_ID,SUM(M.PRICE) AS MONEY_SPENT
FROM SALES S LEFT JOIN MENU M ON S.PRODUCT_ID=M.PRODUCT_ID GROUP BY S.CUSTOMER_ID;
/*
A	76
B	74
C	36
*/

-- How many days has each customer visited the restaurant?
SELECT S.CUSTOMER_ID,COUNT(S.CUSTOMER_ID) AS FREQ FROM SALES S GROUP BY S.CUSTOMER_ID;
/*
A	6
B	6
C	3
*/
-- What was the first item from the menu purchased by each customer?

SELECT * FROM SALES;
SELECT * FROM MEMBERS;
SELECT * FROM MENU;

WITH CTE AS(
SELECT S.*,M.PRODUCT_NAME,row_number() OVER(
PARTITION BY S.CUSTOMER_ID) AS RNK
FROM SALES S LEFT JOIN MENU M ON S.PRODUCT_ID=M.PRODUCT_ID)
SELECT CTE.CUSTOMER_ID,CTE.PRODUCT_ID,CTE.PRODUCT_NAME FROM CTE WHERE CTE.RNK=1 GROUP BY 
CTE.CUSTOMER_ID;

/*
A	1	sushi
B	2	curry
C	3	ramen
*/

-- What is the most purchased item on the menu and how many times was it purchased by all customers?

SELECT * FROM SALES;
SELECT * FROM MEMBERS;
SELECT * FROM MENU;

SELECT S.PRODUCT_ID, M.PRODUCT_NAME, COUNT(S.ORDER_DATE) AS QTY_SOLD FROM SALES S LEFT JOIN MENU M 
ON S.PRODUCT_ID=M.PRODUCT_ID GROUP BY S.PRODUCT_ID ORDER BY QTY_SOLD DESC;

-- Which item was the most popular for each customer?
SELECT * FROM SALES;

WITH CTE AS(
WITH T1 AS(
SELECT S.CUSTOMER_ID, 
	   S.PRODUCT_ID,
	   M.PRODUCT_NAME,
       COUNT(S.PRODUCT_ID) AS QTY
FROM SALES S LEFT JOIN MENU M ON S.PRODUCT_ID=M.PRODUCT_ID GROUP BY S.CUSTOMER_ID,S.PRODUCT_ID)

SELECT T1.*, DENSE_RANK() OVER(PARTITION BY T1.CUSTOMER_ID ORDER BY T1.QTY DESC) AS RANKING
FROM T1)

SELECT CTE.CUSTOMER_ID, CTE.PRODUCT_NAME FROM CTE WHERE CTE.RANKING=1 
GROUP BY CTE.CUSTOMER_ID;
/*
A	ramen
B	curry
C	ramen
*/

-- Which item was purchased first by the customer after they became a member?

SELECT * FROM SALES;
SELECT * FROM MEMBERS;
SELECT * FROM MENU;

WITH T1 AS(
SELECT S.*,ROW_NUMBER() OVER(PARTITION BY S.CUSTOMER_ID) AS ROW_NUM
FROM SALES S)
SELECT T1.CUSTOMER_ID,T1.PRODUCT_ID,M.PRODUCT_NAME,T1.ORDER_DATE
FROM T1 LEFT JOIN MENU M ON T1.PRODUCT_ID=M.PRODUCT_ID WHERE T1.ROW_NUM=2 
GROUP BY T1.CUSTOMER_ID;

/*
A	2	curry	2021-01-01
B	2	curry	2021-01-02
C	3	ramen	2021-01-01

*/
-- If each $1 spent equates to 10 points and sushi has a 2x points multiplier - how many points would each customer have?

SELECT * FROM SALES;
WITH T4 AS(
WITH T3 AS(
WITH T2 AS
(
		WITH T1 AS
        (
				SELECT PRODUCT_ID, PRODUCT_NAME, PRICE, 
				(CASE WHEN PRODUCT_NAME='sushi' THEN PRICE*20 ELSE PRICE*10 END) AS NEW_PRICE
				FROM MENU
        )
		SELECT S.CUSTOMER_ID,S.PRODUCT_ID,T1.PRODUCT_NAME,T1.NEW_PRICE,
        COUNT(S.PRODUCT_ID) AS QTY
		FROM SALES S LEFT JOIN T1 ON S.PRODUCT_ID=T1.PRODUCT_ID
		GROUP BY S.CUSTOMER_ID,S.PRODUCT_ID
)
SELECT T2.*,
(T2.NEW_PRICE*T2.QTY) AS MONEY_PAID
FROM T2)
SELECT T3.*,ROUND((T3.MONEY_PAID/10)) AS POINTS_ACHEIVED
FROM T3)
SELECT T4.CUSTOMER_ID,SUM(T4.POINTS_ACHEIVED) AS TOTAL_POINTS_ACHEIVED 
FROM T4 GROUP BY T4.CUSTOMER_ID; 

/*
A	86
B	94
C	36
*/
USE PROBLEMS;

SELECT * FROM customer_orders;
SELECT * FROM PIZZA_NAMES;
SELECT * FROM PIZZA_RECIPES;
SELECT * FROM PIZZA_TOPPINGS;
SELECT * FROM RUNNER_ORDERS WHERE CANCELLATION=NULL;
SELECT * FROM RUNNERS;


DROP TABLE IF EXISTS runner_orders;
CREATE TABLE runner_orders (
  order_id INTEGER,
  runner_id INTEGER,
  pickup_time VARCHAR(19),
  distance VARCHAR(7),
  duration VARCHAR(10),
  cancellation VARCHAR(23)
);
INSERT INTO runner_orders

VALUES
  ('1', '1', '2020-01-01 18:15:34', '20km', '32 minutes', ''),
  ('2', '1', '2020-01-01 19:10:54', '20km', '27 minutes', ''),
  ('3', '1', '2020-01-03 00:12:37', '13.4km', '20 mins', NULL),
  ('4', '2', '2020-01-04 13:53:03', '23.4', '40', NULL),
  ('5', '3', '2020-01-08 21:10:57', '10', '15', NULL),
  ('6', '3', 'null', 'null', 'null', 'Restaurant Cancellation'),
  ('7', '2', '2020-01-08 21:30:45', '25km', '25mins', 'null'),
  ('8', '2', '2020-01-10 00:15:02', '23.4 km', '15 minute', 'null'),
  ('9', '2', 'null', 'null', 'null', 'Customer Cancellation'),
  ('10', '1', '2020-01-11 18:50:20', '10km', '10minutes', 'null');
  
  
SELECT * FROM RUNNER_ORDERS;

-- CLEANING TABLE RUNNER_ORDERS BY CREATING A TEMPORARY TABLE 

CREATE TEMPORARY TABLE TEMP_RUNNER_ORDERS(
SELECT  ORDER_ID,
		RUNNER_ID,
        (CASE 
        WHEN PICKUP_TIME LIKE '%null%' THEN '0000-00-00 00:00:00' ELSE PICKUP_TIME END) AS PICKUP_TIME,
		(CASE
        WHEN DISTANCE LIKE '%null%' THEN 0
        WHEN DISTANCE LIKE '%km%' THEN TRIM('km' FROM DISTANCE) ELSE DISTANCE END) AS DISTANCE,
        
        
        (CASE
		WHEN DURATION LIKE '%null%' THEN 0
        WHEN DURATION LIKE '% minutes%' THEN TRIM(' minutes' FROM DURATION)
		WHEN DURATION LIKE '%mins%' THEN TRIM('mins' FROM DURATION)
        WHEN DURATION LIKE '% mins%' THEN TRIM(' mins' FROM DURATION)
        WHEN DURATION LIKE '% minute%' THEN TRIM(' minute' FROM DURATION)
        WHEN DURATION LIKE '%minutes%' THEN TRIM('minutes' FROM DURATION) ELSE DURATION END) AS DURATION,
        
        
        (CASE
        WHEN  CANCELLATION IS NULL OR CANCELLATION LIKE '%null%' THEN ' ' ELSE CANCELLATION END) 
        AS CANCELLATION
		
        FROM RUNNER_ORDERS);

SELECT * FROM RUNNER_ORDERS;
SELECT * FROM TEMP_RUNNER_ORDERS;
DROP TABLE TEMP_RUNNER_ORDERS;

-- CLEANING CUSTOMER_ORDERS TABLE BY CREATING A TEMPORARY TABLE TEMP_CUSTOMER_ORDERS

SELECT * FROM CUSTOMER_ORDERS;
CREATE TEMPORARY TABLE TEMP_CUSTOMER_ORDERS(
	SELECT ORDER_ID,
		   CUSTOMER_ID,
           PIZZA_ID,
           (CASE WHEN EXCLUSIONS LIKE '%null%' THEN ' ' ELSE EXCLUSIONS END) AS EXCLUSIONS,
           (CASE WHEN EXTRAS LIKE '%null%' THEN ' '
				 WHEN EXTRAS IS NULL THEN ' ' ELSE EXTRAS END) AS EXTRAS,
			ORDER_TIME FROM CUSTOMER_ORDERS);

SELECT * FROM CUSTOMER_ORDERS;
SELECT * FROM TEMP_CUSTOMER_ORDERS;
DROP TABLE TEMP_CUSTOMER_ORDERS;

SELECT * FROM RUNNER_ORDERS;
SELECT * FROM TEMP_RUNNER_ORDERS;

ALTER TABLE temp_runner_orders
MODIFY COLUMN pickup_time DATETIME,
MODIFY COLUMN distance FLOAT,
MODIFY COLUMN duration INT;



