USE PROBLEMS;
-- What is the total amount each customer spent at the restaurant?
SELECT * FROM SALES;
SELECT * FROM MEMBERS;
SELECT * FROM MENU;

SELECT S.CUSTOMER_ID,SUM(M.PRICE) AS MONEY_SPENT
FROM SALES S LEFT JOIN MENU M ON S.PRODUCT_ID=M.PRODUCT_ID GROUP BY S.CUSTOMER_ID;
/*
A	76
B	74
C	36
*/

-- How many days has each customer visited the restaurant?
SELECT S.CUSTOMER_ID,COUNT(S.CUSTOMER_ID) AS FREQ FROM SALES S GROUP BY S.CUSTOMER_ID;
/*
A	6
B	6
C	3
*/
-- What was the first item from the menu purchased by each customer?

SELECT * FROM SALES;
SELECT * FROM MEMBERS;
SELECT * FROM MENU;

WITH CTE AS(
SELECT S.*,M.PRODUCT_NAME,row_number() OVER(
PARTITION BY S.CUSTOMER_ID) AS RNK
FROM SALES S LEFT JOIN MENU M ON S.PRODUCT_ID=M.PRODUCT_ID)
SELECT CTE.CUSTOMER_ID,CTE.PRODUCT_ID,CTE.PRODUCT_NAME FROM CTE WHERE CTE.RNK=1 GROUP BY 
CTE.CUSTOMER_ID;

/*
A	1	sushi
B	2	curry
C	3	ramen
*/

-- What is the most purchased item on the menu and how many times was it purchased by all customers?

SELECT * FROM SALES;
SELECT * FROM MEMBERS;
SELECT * FROM MENU;

SELECT S.PRODUCT_ID, M.PRODUCT_NAME, COUNT(S.ORDER_DATE) AS QTY_SOLD FROM SALES S LEFT JOIN MENU M 
ON S.PRODUCT_ID=M.PRODUCT_ID GROUP BY S.PRODUCT_ID ORDER BY QTY_SOLD DESC;

-- Which item was the most popular for each customer?
SELECT * FROM SALES;

WITH CTE AS(
WITH T1 AS(
SELECT S.CUSTOMER_ID, 
	   S.PRODUCT_ID,
	   M.PRODUCT_NAME,
       COUNT(S.PRODUCT_ID) AS QTY
FROM SALES S LEFT JOIN MENU M ON S.PRODUCT_ID=M.PRODUCT_ID GROUP BY S.CUSTOMER_ID,S.PRODUCT_ID)

SELECT T1.*, DENSE_RANK() OVER(PARTITION BY T1.CUSTOMER_ID ORDER BY T1.QTY DESC) AS RANKING
FROM T1)

SELECT CTE.CUSTOMER_ID, CTE.PRODUCT_NAME FROM CTE WHERE CTE.RANKING=1 
GROUP BY CTE.CUSTOMER_ID;
/*
A	ramen
B	curry
C	ramen
*/

-- Which item was purchased first by the customer after they became a member?

SELECT * FROM SALES;
SELECT * FROM MEMBERS;
SELECT * FROM MENU;

WITH T1 AS(
SELECT S.*,ROW_NUMBER() OVER(PARTITION BY S.CUSTOMER_ID) AS ROW_NUM
FROM SALES S)
SELECT T1.CUSTOMER_ID,T1.PRODUCT_ID,M.PRODUCT_NAME,T1.ORDER_DATE
FROM T1 LEFT JOIN MENU M ON T1.PRODUCT_ID=M.PRODUCT_ID WHERE T1.ROW_NUM=2 
GROUP BY T1.CUSTOMER_ID;

/*
A	2	curry	2021-01-01
B	2	curry	2021-01-02
C	3	ramen	2021-01-01

*/
-- If each $1 spent equates to 10 points and sushi has a 2x points multiplier - how many points would each customer have?

SELECT * FROM SALES;
WITH T4 AS(
WITH T3 AS(
WITH T2 AS
(
		WITH T1 AS
        (
				SELECT PRODUCT_ID, PRODUCT_NAME, PRICE, 
				(CASE WHEN PRODUCT_NAME='sushi' THEN PRICE*20 ELSE PRICE*10 END) AS NEW_PRICE
				FROM MENU
        )
		SELECT S.CUSTOMER_ID,S.PRODUCT_ID,T1.PRODUCT_NAME,T1.NEW_PRICE,
        COUNT(S.PRODUCT_ID) AS QTY
		FROM SALES S LEFT JOIN T1 ON S.PRODUCT_ID=T1.PRODUCT_ID
		GROUP BY S.CUSTOMER_ID,S.PRODUCT_ID
)
SELECT T2.*,
(T2.NEW_PRICE*T2.QTY) AS MONEY_PAID
FROM T2)
SELECT T3.*,ROUND((T3.MONEY_PAID/10)) AS POINTS_ACHEIVED
FROM T3)
SELECT T4.CUSTOMER_ID,SUM(T4.POINTS_ACHEIVED) AS TOTAL_POINTS_ACHEIVED 
FROM T4 GROUP BY T4.CUSTOMER_ID; 

/*
A	86
B	94
C	36
*/



